### ISSUE TITLE
Saving Config error

### ISSUE THREAD

**Issue by mikusgszyp** [MistyAI/MistyFN#2]
code : 
Traceback (most recent call last):
  File "src/main.py", line 154, in <module>
    main()
  File "src/main.py", line 134, in main
    sensitivity_setup()
  File "src/main.py", line 72, in sensitivity_setup
    with open("src/configs/config.json", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'src/configs/config.json'
Press any key to continue . . .

I think you just need to add connfig.json to files

**Comment by dewPrzemuS** [comment]
This error is caused by having no configs folder which is included in the source code, since config.json is created automatically.
**Make sure you run MistyFN via start.vbs and not directly from some IDE or other executable.**
Protection has been added against situations where someone accidentally deletes the folder, but **running MistyFN from somewhere else than the start.vbs file will never be supported**.
